// Generated by CoffeeScript 1.7.1
var app, db, env, logging, _ref;

_ref = module.parent.exports.require_tree('./config', {
  preserve_filenames: true,
  packages: module.parent.exports.packages
}), app = _ref.app, db = _ref.db, logging = _ref.logging;

module.parent.exports.extendTree({
  config: {
    env: env = process.env.NODE_ENV || app.env,
    view_engine: app.view_engine,
    paths: app.paths,
    host: process.env.HOST || app.host[env] || '0.0.0.0',
    port: process.env.PORT || app.port[env] || 3000,
    db: db[env]
  }
});
