// Generated by CoffeeScript 1.7.1
exports.GUID = function() {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    var r;
    return ((r = Math.random() * 16 | 0) >= 0 && c === 'x' ? r : r & 0x3 | 0x8).toString(16);
  });
};
